/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/components/myVC/404.vue')['default']
    ChangeSkin: typeof import('./src/components/MyMainMenu/changeSkin/index.vue')['default']
    ColorBlock: typeof import('./src/components/myVC/ColorBlock.vue')['default']
    ColorPick: typeof import('./src/components/ColorPick.vue')['default']
    Comment: typeof import('./src/components/myVC/Comment.vue')['default']
    CommentList: typeof import('./src/components/myVC/CommentList.vue')['default']
    DetailSmallBlock: typeof import('./src/components/myVC/DetailSmallBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Emoji: typeof import('./src/components/myVC/WriteCommit/emoji/index.vue')['default']
    FixRoute: typeof import('./src/components/myVC/FixRoute.vue')['default']
    FloatTag: typeof import('./src/components/myVC/FloatTag.vue')['default']
    LeftBlock: typeof import('./src/components/myVC/LeftBlock.vue')['default']
    LineMusic: typeof import('./src/components/myVC/LineMusic/index.vue')['default']
    Loading: typeof import('./src/components/myVC/Loading.vue')['default']
    LoadingBig: typeof import('./src/components/myVC/LoadingBig.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MusicRadio: typeof import('./src/components/MusicRadio/index.vue')['default']
    MyDialog: typeof import('./src/components/myVC/MyDialog.vue')['default']
    MyMainMenu: typeof import('./src/components/MyMainMenu/index.vue')['default']
    PersonalMessage: typeof import('./src/components/MyMainMenu/PersonalMessage/index.vue')['default']
    PlayingPointOut: typeof import('./src/components/myVC/PlayingPointOut.vue')['default']
    PlayListPanel: typeof import('./src/components/MusicRadio/playListPanel/index.vue')['default']
    PlayListShow: typeof import('./src/components/myVC/PlayListShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScroolLrc: typeof import('./src/components/myVC/ScroolLrc.vue')['default']
    Singer: typeof import('./src/components/myVC/LineMusic/Singer/index.vue')['default']
    SmallBlock: typeof import('./src/components/myVC/SmallBlock.vue')['default']
    SmallTips: typeof import('./src/components/myVC/smallTips.vue')['default']
    SongDetail: typeof import('./src/components/MusicRadio/songDetail/index.vue')['default']
    Tag: typeof import('./src/components/myVC/Tag.vue')['default']
    WriteCommit: typeof import('./src/components/myVC/WriteCommit/index.vue')['default']
    ZhuanJi: typeof import('./src/components/myVC/LineMusic/ZhuanJi/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
