/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSmall: typeof import('./src/components/AppSmall.vue')['default']
    ChangeSkin: typeof import('./src/components/MyMainMenu/changeSkin/index.vue')['default']
    ColorBlock: typeof import('./src/components/myVC/ColorBlock.vue')['default']
    ColorPick: typeof import('./src/components/ColorPick.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoadingBig: typeof import('./src/components/myVC/LoadingBig.vue')['default']
    MyMainMenu: typeof import('./src/components/MyMainMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/myVC/Tag.vue')['default']
  }
}
